### ISSUE TITLE
[meta] Next: track operations to merge into production

### ISSUE THREAD

**Issue by bfabio** [italia/designers.italia.it#695]
This is a meta issue that documents our plan to publish to production (steps, what to do, in what order, etc.)

- [x] Decide exact date & time for the operations, preferably **not during working hours**
  📆Candidate: Thrusday, 11th of May 21–23
- [x] Prepare all the items below so that they're ready to be carried out immediately
- [x] ⚠️Remove the old Jekyll site from Vercel. :information_source: **No previews or new commits for the old site from this point onward** :information_source: 
- [x] Remove news (#768) 
- [x] Support matomo configuration
  - [x] Merge #723
  - [x]  Close #716
- [x] Switch to Node 18
  - [x] Merge #721 (ready to merge :heavy_check_mark:)
  - [x] Close #645
- [x] Conditionally show the banner: no banner for production and banner when navigating on prossima.d.i.i explaining the site is live at the other URL
  - [x] Merge #720 (ready to merge :heavy_check_mark:)
  - [x] Close #653
- [x] Setup deploy GitHub actions
  - [x] Double check #634
  - [x] Set Matomo production environment variables in GitHub build env
  - [x] Merge #634 (~~:construction: need to uncomment the commented parts and set the domain in the PR :construction:~~)
   - [x] Close #613
- [x] Add an initial "clean" commit to rebase all next... 
- [x] Locally merge `next` into `main` and check if everything is ok
  ```
  git checkout next
  git merge -s ours main
  git checkout main
  git merge next
  ls
  npm ci
  npm run clean && npm run develop
  ```
- [x] :warning: Merge `next` into `main` upstream :warning: **HERE BE DRAGONS**
  * Potentially needs a couple minutes for GitHub Pages to distribute the content
  *  If something goes foobar we can immediately revert the [gh-pages branch](https://github.com/italia/designers.italia.it/commits/gh-pages) manually
- [x] Set prossima.d.i.i to point to `main` in Vercel instead of `next`, set the correct build script and node version
- [x] Check Matomo is correctly tracking the main site and prossima.d.i.i
- [ ] Check that #530 works and close it
- [x] Remove `next`, `next-backup`, `main-backup`
- [x] Update the README
