### ISSUE TITLE
Next: meta issue to track a quick response to the first set of usability test results

### ISSUE THREAD

**Issue by Fupete** [italia/designers.italia.it#750]
Quick fixes/improvements: 
- [x] **Publish archives and tag features** 
✅ released a couple of weeks ago. 
- [x] **Remove temporary disclaimers on design system indexes** 
👁️ under review here https://github.com/italia/designers.italia.it/pull/747
- [x] **Improve megamenu + a11y issue** 
 🙅 under review here https://github.com/italia/designers.italia.it/pull/700
 ⚒️ working on a new PR here #752 
- [x] **Improve readability of Kangaroo components** 
👁️ under review here https://github.com/italia/designers.italia.it/pull/749
- [x] **Improve readability of "Norme e riferimenti"** and layout of theEditorial section 
🛠️ working on a PR here https://github.com/italia/designers.italia.it/pull/770
 
 cc @danielaiozzo
